# @format

name: Sync API Scripts

on:
  push:
    branches:
      - main
      - sync-apis-copy-multiple-test
    paths:
      - resources/api/tiny-games/scripts/games/**
      - .github/workflows/sync-apis.yml

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push App API
        uses: c0mplexity0/copy_file_pattern_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_pattern: 'resources/api/tiny-games/scripts/games/!(tiny-games.web).@(js|mjs|d.ts|d.mts)'
          destination_repo: 'c0mplexity0/tiny-games-app'
          destination_folder: ""
          user_email: '106925362+C0mplexity0@users.noreply.github.com'
          user_name: 'C0mplexity0'
          commit_message: ${{ github.event.head_commit.message }}
          git_server: "github.com"


      - name: Push Web API
        uses: c0mplexity0/copy_file_pattern_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source_pattern: 'resources/api/tiny-games/scripts/games/!(tiny-games.app).@(js|mjs|d.ts|d.mts)'
          destination_repo: 'c0mplexity0/tiny-games-web'
          destination_folder: ""
          user_email: '106925362+C0mplexity0@users.noreply.github.com'
          user_name: 'C0mplexity0'
          commit_message: ${{ github.event.head_commit.message }}
          git_server: "github.com"
